name: test
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    strategy:
      matrix:
        go-version: ['1.25', '1.26']
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Test
      run: go test -race -cover ./...
      if: runner.os != 'Windows'
    - name: Test (Windows)
      run: go test -cover ./...
      if: runner.os == 'Windows'
